name: Test
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: action-alphavantage-time-series-stock-api
        id: api
        uses: strong-gemi/action-alphavantage-time-series-stock-api@master
        with:
          function: 'GLOBAL_QUOTE'
          symbol: 'PLTR'
      - name: Get the output GQ-price
        run: echo "res!! - ${{ steps.api.outputs.GQ-price }}"